spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

token:
  jwt:
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}
    secret: ${JWT_SECRET}
