version: '3.4'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    networks:
      - microservice-app-network
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5005:5005"
    command: [
      "java",
      "-Xmx2048m",
      "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005",
      "-jar",
      "/app.jar",
      "--server.port=8080"
    ]
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - microservice-app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - microservice-app-network
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  microservice-app-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: