CREATE TABLE IF NOT EXISTS USERS
(
    ID              UUID            NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    EMAIL           TEXT            NOT NULL UNIQUE,
    ROLE            VARCHAR(30)     NOT NULL CHECK (ROLE IN ('ROLE_USER', 'ROLE_ADMIN')),
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);