CREATE TABLE IF NOT EXISTS TOKENS
(
    ID              UUID            NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    JWT             TEXT            NOT NULL UNIQUE,
    TYPE            VARCHAR(30)     NOT NULL CHECK (TYPE IN ('ACCESS', 'REFRESH')),
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID         UUID            NOT NULL REFERENCES USERS(ID)
);
