CREATE TABLE IF NOT EXISTS PASSWORDS
(
    ID                  UUID           NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID             UUID           NOT NULL REFERENCES USERS(ID),
    PASSWORD            TEXT           NOT NULL,
    CREATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);